apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-secret
  template:
    metadata:
      labels:
        app: flask-secret
    spec:
      containers:
        - name: flask
          image: flask-secret-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: conjur-secret
              mountPath: /secrets/conjur-secret.txt
              readOnly: true
      volumes:
        - name: conjur-secret
          hostPath:
            path: /opt/conjur/conjur-secret.txt
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: flask-secret-svc
spec:
  selector:
    app: flask-secret
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31333  # or any port between 30000–32767

